version: '3.8'

services:
  api:
    build: .
    container_name: digital-twin-api
    ports:
      - "8000:8000"
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883
    depends_on:
      - postgres-twin
      - mqtt-broker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: digital-twin-frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"  # Removido 127.0.0.1 para acesso entre containers
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  mqtt-subscriber:
  build: .
  container_name: mqtt-subscriber
  command: python mqtt_subscriber.py
  environment:
    - MQTT_BROKER_HOST=mqtt-broker
  depends_on:
    - mqtt-broker

  postgres-twin:
    image: postgres:15
    container_name: postgres-twin
    environment:
      - POSTGRES_USER=twin
      - POSTGRES_PASSWORD=twin
      - POSTGRES_DB=twin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  mosquitto_data:
  mosquitto_log:
  pgdata:
